"""Stages 1-2 — the situations and the dialogues written from them.

Both stages are unchanged between 1.0 and 2.0: 20 EmpatheticDialogues situations labelled
`embarrassed`, each turned once into a 4-8 turn conversation whose words must not settle
whether the story is funny or bleak. So 2.0 takes them from 1.0 rather than paying to write
the same thing again, which also makes the two versions directly comparable -- the same
conversations, differing only in what 2.0 does downstream.

That reuse is only sound if the words still match the audio, so this checks every turn against
the take recorded for it in 1.0 and refuses to import if any disagree.

    python 2.0/dialogues.py
    python 2.0/dialogues.py --check      # verify the reuse without writing
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
PRIOR = REPO / "1.0" / "out"
OUT = HERE / "out"

KEEP = ("conv_id", "item_id", "situation", "situation_third_person")

# 1.0 keys its per-turn takes and word alignments by the audio path they were rendered to.
TAKE = "out/audio_turns/{item}_t{index:02d}_{speaker}.mp3"


def load_prior() -> tuple[list[dict], dict, dict]:
    transcripts = json.loads((PRIOR / "transcripts.json").read_text())
    turn_texts = json.loads((PRIOR / "turn_texts.json").read_text())
    alignment = json.loads((PRIOR / "turn_alignment.json").read_text())
    return transcripts["items"], turn_texts, alignment


def check(items: list[dict], turn_texts: dict, alignment: dict) -> list[str]:
    """Every turn must match the take that was rendered for it, and have an alignment."""
    problems = []
    for item in items:
        for index, turn in enumerate(item["turns"], start=1):
            take = TAKE.format(item=item["item_id"], index=index, speaker=turn["speaker"])
            recorded = turn_texts.get(take)
            if recorded is None:
                problems.append(f"{take}: no recorded take")
            elif recorded.strip() != turn["text"].strip():
                problems.append(f"{take}: text differs from the rendered take")
            if take not in alignment:
                problems.append(f"{take}: no character alignment")
    return problems


def takes(item: dict, alignment: dict):
    """Each turn paired with the take that was rendered for it."""
    for index, turn in enumerate(item["turns"], start=1):
        yield TAKE.format(item=item["item_id"], index=index,
                          speaker=turn["speaker"]), turn


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    items, turn_texts, alignment = load_prior()
    problems = check(items, turn_texts, alignment)
    turns = sum(len(i["turns"]) for i in items)
    print(f"1.0 carries {len(items)} items · {turns} turns")
    if problems:
        print(f"\n{len(problems)} problem(s) — not importing:")
        for line in problems[:20]:
            print(f"  {line}")
        raise SystemExit(1)
    print("every turn matches its rendered take and has a character alignment")
    if args.check:
        return

    OUT.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "1.0/out/transcripts.json",
        "note": ("Stages 1-2 are identical in 1.0 and 2.0, so the situations and dialogues are "
                 "reused verbatim. Everything downstream — density, placement, gold, clips, "
                 "verification, splicing — is regenerated by 2.0."),
        "turn_range": [min(len(i["turns"]) for i in items),
                       max(len(i["turns"]) for i in items)],
        "items": [dict({k: item[k] for k in KEEP},
                       turns=[dict(turn, take=take, words=len(alignment[take]))
                              for take, turn in takes(item, alignment)])
                  for item in items],
    }
    (OUT / "items.json").write_text(json.dumps(payload, indent=2) + "\n")
    counts = {}
    for item in items:
        counts[len(item["turns"])] = counts.get(len(item["turns"]), 0) + 1
    print(f"\nout/items.json · {len(items)} items")
    print("  turns:", ", ".join(f"{n} turns x{c}" for n, c in sorted(counts.items())))


if __name__ == "__main__":
    main()
